version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: urlbriefr-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your_secret_key_here
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/urlbriefr
    depends_on:
      - db

  # Frontend service
  frontend:
    build: ./frontend
    container_name: urlbriefr-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  # Database service
  db:
    image: postgres:13
    container_name: urlbriefr-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlbriefr
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: 