# Generated by Django 5.2.1 on 2025-05-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shortenedurl'),
        ),
    ]
