# Generated by Django 5.2.2 on 2025-06-06 22:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('shortener', '0006_rename_redirect_page_title_shortenedurl_custom_redirect_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('visitor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('reached_destination', models.BooleanField(default=False)),
                ('completed_action', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='shortener.shortenedurl')),
            ],
            options={
                'ordering': ['-last_visit'],
                'unique_together': {('url', 'session_id')},
            },
        ),
    ]
