# Generated by Django 5.2.2 on 2025-06-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='is_ab_test',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ABTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_url', models.URLField(max_length=2000)),
                ('weight', models.PositiveIntegerField(default=50)),
                ('name', models.CharField(default='Variant', max_length=100)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shortener.shortenedurl')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
