# Generated by Django 5.2.2 on 2025-06-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortenedurl_folder_tag_shortenedurl_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='show_splash_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='splash_page_animation_type',
            field=models.CharField(blank=True, choices=[('rocket', 'Rocket'), ('workers', 'Workers'), ('pulse', 'Pulse'), ('none', 'None')], default='rocket', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='splash_page_background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='splash_page_button_color',
            field=models.CharField(blank=True, default='#3B82F6', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='splash_page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='splash_page_logo_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='splash_page_redirect_delay',
            field=models.PositiveIntegerField(default=3, help_text='Redirect delay in seconds'),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='splash_page_text_color',
            field=models.CharField(blank=True, default='#000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='splash_page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
