# Generated by Django 5.2.2 on 2025-06-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_shortenedurl_show_splash_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='splash_page_redirect_delay',
            new_name='redirect_delay',
        ),
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='splash_page_description',
            new_name='redirect_page_description',
        ),
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='splash_page_title',
            new_name='redirect_page_title',
        ),
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='show_splash_page',
            new_name='use_custom_redirect',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='splash_page_animation_type',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='splash_page_background_color',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='splash_page_button_color',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='splash_page_logo_url',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='splash_page_text_color',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='animation_type',
            field=models.CharField(choices=[('rocket', 'Rocket'), ('workers', 'Workers'), ('loading', 'Simple Loading'), ('none', 'No Animation')], default='rocket', max_length=20),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='brand_color',
            field=models.CharField(default='#3B82F6', help_text='Primary brand color (hex code)', max_length=20),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='brand_logo',
            field=models.URLField(blank=True, help_text='URL to brand logo image', max_length=2000, null=True),
        ),
    ]
