# Generated by Django 5.2.2 on 2025-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_rename_splash_page_redirect_delay_shortenedurl_redirect_delay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='redirect_page_title',
            new_name='custom_redirect_message',
        ),
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='use_custom_redirect',
            new_name='use_redirect_page',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='animation_type',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='brand_color',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='redirect_page_description',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='brand_logo_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='redirect_page_type',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('rocket', 'Rocket Animation'), ('working', 'People Working'), ('digging', 'Digging Animation')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='redirect_delay',
            field=models.PositiveSmallIntegerField(default=3, help_text='Delay in seconds before redirecting'),
        ),
    ]
