# Generated by Django 5.2.2 on 2025-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_rename_redirect_page_title_shortenedurl_custom_redirect_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='encryption_key',
            field=models.CharField(blank=True, help_text='Encryption key for this URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether the destination URL is encrypted'),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='max_clicks',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of clicks before the link self-destructs', null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='self_destruct',
            field=models.BooleanField(default=False, help_text='Whether the link should self-destruct'),
        ),
    ]
