# Generated by Django 5.2.2 on 2025-06-07 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_rename_redirect_page_title_shortenedurl_custom_redirect_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoofingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('short_code', models.CharField(max_length=15)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='The original URL this was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='shortener.shortenedurl'),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='enable_ip_restrictions',
            field=models.BooleanField(default=False, help_text='Enable IP-based access control'),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='integrity_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash to verify URL integrity', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='spoofing_protection',
            field=models.BooleanField(default=False, help_text='Enable protection against link spoofing'),
        ),
        migrations.CreateModel(
            name='IPRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('allow', 'Allow List'), ('block', 'Block List')], default='block', max_length=10)),
                ('ip_address', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='ip_restrictions',
            field=models.ManyToManyField(blank=True, related_name='urls', to='shortener.iprestriction'),
        ),
    ]
