# Generated by Django 5.0.1 on 2025-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_remove_shortenedurl_is_one_time_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark URL as favorite for quick access'),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='security_issues',
            field=models.JSONField(blank=True, help_text='Details of security issues found', null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='security_scan_date',
            field=models.DateTimeField(blank=True, help_text='When the security scan was performed', null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='security_scan_result',
            field=models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious'), ('unknown', 'Unknown'), ('pending', 'Pending Scan')], default='pending', help_text='Result of malware/spam scan', max_length=20),
        ),
    ]
